<?php
$helper = $this->helper('Inferendo\Visidea\Helper\Data');
if ($helper->isEnabled()):
    $public_token = $helper->getConfig('general','public_token');
    $website = $helper->getConfig('general','website');

    $currentFullAction = $block->getRequest()->getFullActionName();
    if ($block->isLoggedIn()) {
        $user_id = $block->getCustomerId();
    } else {
        $user_id = '';
    }
    if ($currentFullAction == 'catalog_product_view' && $currentProduct = $block->getCurrentProduct()) {
        $product_id = $currentProduct->getId();
    } else {
        $product_id = 0;
    }

    $page = 'other';
    switch ($currentFullAction){
        case 'cms_index_index':
            $page = 'home';
            break;
        case 'catalog_product_view':
            $page = 'product';
            break;
        case 'checkout_cart_index':
            $page = 'cart';
            break;
        case 'checkout_onepage_success':
            $page = 'order';
            break;
    }
?>

<?php if ($page == 'home'): ?>
    <div class="visidea-recommendations" page="home" user_id="<?php echo $user_id; ?>"></div>
<?php endif; ?>
<?php if ($page == 'product'): ?>
    <div class="visidea-recommendations" page="product" user_id="<?php echo $user_id; ?>" item_id="<?php echo $product_id; ?>"></div>
    <meta class="visidea-interaction" type="item" user_id="<?php echo $user_id; ?>" item_id="<?php echo $product_id; ?>" />
<?php endif; ?>
<?php if ($page == 'cart'): ?>
    <div class="visidea-recommendations" page="cart" user_id="<?php echo $user_id; ?>"></div>
<?php endif; ?>
<?php if ($page == 'order'): ?>
    <div class="visidea-recommendations" page="order" user_id="<?php echo $user_id; ?>"></div>
<?php endif; ?>

    <div class="visidea-search-bar" user_id="<?php echo $user_id; ?>"></div>

    <script type="text/javascript">
        require(["Visidea"], function (Visidea) {
            window.onload = function() {
                visidea('<?php echo $website ?>', '<?php echo $public_token ?>');
            };
        });
    </script>

<?php endif; ?>