<?php
$helper = $this->helper('Inferendo\Visidea\Helper\Data');
if ($helper->isEnable()):
    $public_token = $helper->getConfig('general','public_token');
    $website = $helper->getConfig('general','website');
    $currentFullAction = $block->getRequest()->getFullActionName();
    if ($block->isLoggedIn()) {
        $user_id = $block->getCustomerId();
    } else {
        $user_id = 0;
    }

    if ($currentFullAction == 'catalog_product_view' && $currentProduct = $block->getCurrentProduct()) {
        $product_id = $currentProduct->getId();
    } else {
        $product_id = 0;
    }

    switch ($currentFullAction){
        case 'catalog_product_view':
            $page = 'product';
            break;
        case 'checkout_cart_index':
            $page = 'cart';
            break;
        case 'checkout_onepage_success':
            $page = 'order';
            break;
        case 'cms_index_index':
            $page = 'home';
            break;
    }
?>


    <div class="block widget block-products-list grid">
        <div class="block-content" id="visidea-cont">


        </div>
    </div>


    <script type="text/javascript">

        require(["Visidea", "VisideaMagento", "jquery", "Slick"], function (Visidea, VisMagento, $) {

            var whenExists = function(name, callback) {
                var interval = 10; // ms
                window.setTimeout(function() {
                    if (eval(name) != undefined) {
                        callback();
                    } else {
                        window.setTimeout(arguments.callee, interval);
                    }
                }, interval);
            }

            function show_slider(){
                $('.products-rec').slick({
                    slidesToShow: 5,
                    slidesToScroll: 1,
                    centerMode: false,
                    arrows: true,
                    autoplay: true,
                    autoplaySpeed: 2000,
                    responsive: [
                        {
                            breakpoint: 1300,
                            settings: {
                                slidesToShow: 4,
                                slidesToScroll: 1,
                            }
                        },
                        {
                            breakpoint: 1000,
                                settings: {
                            slidesToShow: 3,
                                slidesToScroll: 1
                        }
                        },
                        {
                            breakpoint: 420,
                                settings: {
                            slidesToShow: 2,
                                slidesToScroll: 1
                        }
                        }
                    ]
                });

            }

            var gc = 1;
            var itemsProcessed = 0;

            function show_product(res){
                if (Array.isArray(res)) {
                    res.forEach(function(item) {
                        var producthtml = '' +
                            '<div>' +
                            '   <div class="product-item" style="width: 100%; padding:10px;">'+
                            '       <div class="product-item-info">'+
                            '           <a href="'+ item.url +'" class="product-item-photo">'+
                            '               <span class="product-image-container" style="width:240px;">'+
                            '                   <span class="product-image-wrapper" style="padding-bottom: 100%;">'+
                            '                       <img class="product-image-photo" src="'+ item.images[0] +'" max-width="240" max-height="300" alt="Radiant Tee">'+
                            '                   </span>'+
                            '               </span>'+
                            '           </a>'+
                            '           <div class="product-item-details">'+
                            '               <strong class="product-item-name">'+
                            '                   <a title="Radiant Tee" href="'+ item.url +'" class="product-item-link">'+
                            '                       '+ item.name +
                            '                   </a>'+
                            '               </strong>'+
                            '               <div class="price-box price-final_price" data-role="priceBox" data-product-id="'+ item.id +'" data-price-box="product-id-'+ item.id +'"><span class="normal-price">'+
                            '                   <span class="price-container price-final_price tax weee">'+
                            '                       <span id="old-price-'+ item.id +'-widget-product-grid" data-price-type="finalPrice" class="price-wrapper"><span class="price">'+ visidea.format_currency(item.price) +'</span></span></span>'+
                            '                   </span>'+
                            '               </div>'+
                            '           </div>'+
                            '       </div>'+
                            '    </div>'+
                            '</div>';

                        var id = 'visidea-products'+gc;
                        document.getElementById(id).innerHTML += producthtml;
                    });
                }
                gc++;
            }


            var visidea = new Visidea.Api('<?= $website ?>', '<?= $public_token ?>');
            whenExists("visidea.conf", function() {

                window.visideaMagento = new VisideaMagento(visidea, '<?= $website ?>', '<?= $public_token ?>');
                var user_id = window.visideaMagento.setUser(<?= $user_id; ?>);
                console.log(user_id)

                <?php if($page == 'product'): ?>
                visidea.item_view("<?= $product_id ?>",user_id);
                <?php endif; ?>

                var cont = 1;
                var n_rec_type = 0;

                visidea.conf.<?= $page; ?>.forEach(function(item) {
                    if (item.show)
                        n_rec_type++;
                });

                visidea.conf.<?= $page; ?>.forEach(function(item) {
                    if (item.show) {
                        var myhtml = '<h2>' + item.title + '</h2><div class="products wrapper grid products-grid products-upsell">' +
                            '                <div id="visidea-products' + cont + '" class="visidea products-rec">' +
                            '                </div>' +
                            '            </div>';
                        document.getElementById("visidea-cont").innerHTML += myhtml;

                        visidea.recommend(item.algo, user_id, "<?= $product_id; ?>", [], item.n,
                            function (res) {
                                show_product(res);
                                itemsProcessed++;
                                console.log('itemsProcessed:'+itemsProcessed)
                                console.log('n_rec_type:'+n_rec_type)
                                if (itemsProcessed == n_rec_type) {
                                    show_slider();
                                }
                            }, []);
                        cont++;
                    }
                });

            });


        });
    </script>

<?php endif; ?>