<?php
/** @var \Inferendo\Visidea\Block\Adminhtml\System\Config\Field\InteractionExport $block */
/** @var Magento\Framework\View\TemplateEngine\Php $block */
?>
<?php if ($block->isEnabled()) { ?>
<tr id="row_order_export_csv">
    <td class="label">
        <label for="row_order_export_csv"><?= $block->getEscaper()->escapeHtml(__('Items CSV link:')) ?></label>
    </td>
    <td class="value"><?= $block->getEscaper()->escapeHtml($block->getItemsExportUrl()) ?></td>
</tr>
<?php } ?>