<?php
/** @var \Inferendo\Visidea\Block\Adminhtml\System\Config\Field\InteractionExport $block */
/** @var Magento\Framework\View\TemplateEngine\Php $this */
?>
<tr id="row_order_export_csv">
    <td class="label">
    </td>
    <td class="value">
        <img src="<?php echo $block->getImageUrl()?>" style="width:350px">
        <hr>
        <p>Visidea is the visual search and visual recommendation plugin for Magento.</p>
        <p>This plugin need an account on Visidea.ai. You can check our plans and pricing <strong><a href="https://visidea.ai/pricing/" target="_blank">here</a></strong>.</p>
        <p>Discover more about our service on our <strong><a href="https://visidea.ai/" target="_blank">website</a></strong>.</p>
        <p>Go to Visidea dashboard to create an account and get the <strong><a href="https://app.visidea.ai/register?cms=magento&website=pippo.myshopify.com" target="_blank">API keys</a></strong>.</p>
        <p>Any problems? contact us <strong><a href="mailto:support@visidea.ai">support@visidea.ai</a></strong>.</p>
    </td>
</tr>

