<?php
/** @var \Recommendify\ShowRecommendations\Block\Adminhtml\System\Config\Field\CronUrl $block */
/** @var Magento\Framework\View\TemplateEngine\Php $this */
?>
<?php if($block->isEnabled()){ ?>
<tr id="row_lable_cron_url">
    <td class="label">
        <label for="row_lable_cron_url"><?php echo __('CronJob Link:')?></label>
        <td class="value"><?php echo $block->getCronUrl()?></td>
    </td>
</tr>
<?php } ?>