<?php
/** @var \Recommendify\ShowRecommendations\Block\Adminhtml\System\Config\Field\InteractionExport $block */
/** @var Magento\Framework\View\TemplateEngine\Php $this */
?>
<?php if($block->isEnabled()){ ?>
<tr id="row_order_export_csv">
    <td class="label">
        <label for="row_order_export_csv"><?php echo __('Users CSV link:')?></label>
        <td class="value"><?php echo $block->getCustomerExportUrl()?></td>
    </td>
</tr>
<?php } ?>